# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC DEV2 Workflow

on:
  push:
    branches:
      - feature/**
    paths:
      - 'Definitions/**'
      - '.github/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to DEV2'
        required: true
        type: choice
        options:
          - dev
          - dev2
          - both
        default: 'dev'

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan epac-dev2
    if: github.event.inputs.environment == 'dev2' || github.event.inputs.environment == 'both'
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: epac-dev2
      planGitHubEnvironment: EPAC-DEV
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployPolicy:
    name: Deploy epac-dev2 Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes'
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: epac-dev2
      planGitHubEnvironment: EPAC-DEV
      #PAC_INPUT_FOLDER: "$(GITHUB_WORKSPACE)/plans-epac-dev2"
      PAC_INPUT_FOLDER: .
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployRoles:
    name: Deploy epac-dev2 Role Changes
    needs: plan
    if: needs.plan.outputs.deployRoleChanges == 'yes'
    uses: ./.github/workflows/deploy-roles.yml
    with:
      pacEnvironmentSelector: epac-dev2
      planGitHubEnvironment: EPAC-DEV
      #PAC_INPUT_FOLDER: "$(GITHUB_WORKSPACE)/plans-epac-dev2"
      PAC_INPUT_FOLDER: .
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  # planProd:
  #   name: Plan epac-prod
  #   needs: [deployPolicy, deployRoles]
  #   uses: ./.github/workflows/plan.yml
  #   with:
  #     pacEnvironmentSelector: epac-prod
  #     planGitHubEnvironment: EPAC-PROD
  #     PAC_OUTPUT_FOLDER: ./Output
  #     PAC_DEFINITIONS_FOLDER: ./Definitions
  #   secrets: inherit