# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC PROD Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'Definitions/**'
  workflow_dispatch: # Manual executions

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan EPAC-PROD
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: epac-prod
      planGitHubEnvironment: EPAC-PROD
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit
  
  approval :
    runs-on: ubuntu-latest
    needs: plan
    steps :
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Wait for approval
      uses: actions/github-script@v5
      with :
        script: |
          const { owner, repo } = context.repo
          const { number } = context.issue
          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number: number,
            body: 'Please review the plan and approve the workflow if everything is correct.'
          })
          await github.rest.actions.createWorkflowApproval({
            owner,
            repo,
            run_id: context.runId,
            event_type : 'APPROVE'
          })

  deployPolicy:
    name: Deploy epac-prod Policy Changes
    needs: [plan,approval]
    if: needs.plan.outputs.deployPolicyChanges == 'yes' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: epac-prod
      planGitHubEnvironment: EPAC-PROD
      PAC_INPUT_FOLDER: .
      #PAC_INPUT_FOLDER: "$(GITHUB_WORKSPACE)/plans-epac-prod"
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployRoles:
    name: Deploy epac-prod Role Changes
    needs: [plan,approval]
    if: needs.plan.outputs.deployRoleChanges == 'yes' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-roles.yml
    with:
      pacEnvironmentSelector: epac-prod
      planGitHubEnvironment: EPAC-PROD
      PAC_INPUT_FOLDER: .
      #PAC_INPUT_FOLDER: "$(GITHUB_WORKSPACE)/plans-epac-prod"
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit