# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC epac-prod Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'Definitions/**'

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan epac-prod
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: epac-prod
      planGitHubEnvironment: EPAC-PROD
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployPolicy:
    name: Deploy epac-prod Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: epac-prod
      planGitHubEnvironment: EPAC-PROD
      PAC_INPUT_FOLDER: "$(GITHUB_WORKSPACE)/plans-epac-prod"
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployRoles:
    name: Deploy epac-prod Role Changes
    needs: plan
    if: needs.plan.outputs.deployRoleChanges == 'yes' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-roles.yml
    with:
      pacEnvironmentSelector: epac-prod
      planGitHubEnvironment: EPAC-PROD
      PAC_INPUT_FOLDER: "$(GITHUB_WORKSPACE)/plans-epac-prod"
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit